# Generated by Django 3.0.5 on 2021-04-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campus_name', models.CharField(max_length=10)),
                ('Campus_location', models.CharField(max_length=10)),
            ],
        ),
    ]
