# Generated by Django 3.0.5 on 2021-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=10)),
                ('Course_name', models.CharField(max_length=10)),
            ],
        ),
    ]
