# Generated by Django 3.0.5 on 2021-04-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
