# Generated by Django 3.0.5 on 2021-04-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0009_auto_20210418_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.TextField(max_length=25)),
                ('Student_email', models.CharField(max_length=20)),
                ('Course_name', models.CharField(max_length=10)),
                ('Subjects', models.CharField(max_length=25)),
                ('Labs', models.CharField(max_length=25)),
                ('Facility', models.CharField(max_length=25)),
                ('Stream', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
